spring.application.name=IstanbulRailRoute

spring.datasource.url=jdbc:postgresql://localhost:5432/istanbul_rail_route
spring.datasource.username=postgres
spring.datasource.password=235689   

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.neo4j.uri=neo4j+s://4f4928f4.databases.neo4j.io
spring.neo4j.authentication.username=4f4928f4
spring.neo4j.authentication.password=Q-dy5Bi8eAjNXRokixdEtNANxd0BOOE6DvsUviCoySU